### ISSUE TITLE
Revision of the "Filter" drop-down menu.

### ISSUE THREAD

**Issue by fylip97** [NovatecConsulting/novatec-k8s-panel#1]
The drop-down menu "Filter" is split into the categories "Namespace", "Deployment", "Pod" and "Container". In these are the different options.
It should be possible to display the different options in alphabetical order.

**Comment by tangerstein** [comment]
Another idea: Split drop down menu in different columns:

![image](https://user-images.githubusercontent.com/13380485/121357768-5960dc80-c932-11eb-84eb-d1347d85212f.png)
