### ISSUE TITLE
Add possibility to add arbitrary metrics

### ISSUE THREAD

**Issue by fylip97** [NovatecConsulting/novatec-k8s-panel#2]
A user should be able to add any metric as query. The panel should then visualize the metrics, which are provided by the user.

**Comment by tangerstein** [comment]
Idea: The queries are named based on a predefined naming convention.

![image](https://user-images.githubusercontent.com/13380485/125915710-e5e9d488-862c-443c-ac7f-6e0af0349626.png)

**Comment by tangerstein** [comment]
Based on todays meeting, we agreed on focusing on the following points:

- Many metrics (e.g. cpu metrics) are collected with three different queries with different groupings.
  We could consolidate these metrics by only using one, which includes the group by clause `(container, pod, namespace)`
- The panel visualization fails, when the basic queries:
   - kube_pod_container_info  
   - count_kube_deployment_labels
   - some of the count values are important as well.
- We should try to establish a naming convention, from which we can derive the name, the grouping as well as the type of the metric:     
![image](https://user-images.githubusercontent.com/13380485/127327300-566e3cda-d0c5-4b87-a25c-d2ed7e551b8d.png)
