### ISSUE TITLE
Revision of the threshold inside the option tab

### ISSUE THREAD

**Issue by salim-1997** [NovatecConsulting/novatec-k8s-panel#31]
While before we used a self made threshold for the options to choose the overload of the metric, some limitations were necessary to accomplish the task. We currently found out about a new @grafana/ui component called 'newThreshold' which is a threshold component that would possibly be more efficient than the self made threshold. Also this new component would possibly give better functionalities and would help with the app being more flexible and dynamic. 
This is the new components documentation:
https://developers.grafana.com/ui/latest/index.html?path=/story/pickers-and-editors-thresholdseditornew--default

**Comment by leoschur** [comment]
I forgot to link this issue in my PR #40
This is implemented by now.
