### ISSUE TITLE
Extension of the sorting function.

### ISSUE THREAD

**Issue by fylip97** [NovatecConsulting/novatec-k8s-panel#5]
Grouping by objects with only infrastructure metrics, objects with only application metrics, and objects with both infrastructure metrics and application metrics should be possible.

**Comment by tangerstein** [comment]
@salim-1997 I'm trying to elaborate this ticket a bit:

We currently have two types of metrics, which are currently visualized in two different panels.
However, the metrics are not available for each and every service.

For instance, in our demo application are a bunch of services, which are not written in Java and therefore not monitored with inspectIT Ocelot. This scenario is pretty realistic. In more complex polyglot architectures often not each and every service can be monitored and instrumented so easily.

The ticket is about evaluating/ elaborating the following:
- How can we show the user, for which services application metrics are available?
- How can we filter by elements, which include application-specific metrics?
