### ISSUE TITLE
Visual representation of the state of individual components.

### ISSUE THREAD

**Issue by fylip97** [NovatecConsulting/novatec-k8s-panel#6]
Through the fourth dropdown menu named "Metric" a metric can be selected. The state of the individual K8s objects is examined with regard to this metric. The state is visualized to the user by the traffic light color model.

**Comment by tangerstein** [comment]
Addition: The highlighting (colors) should be configurable. It should as the color mapping configuration of the single stat panel:

![image](https://user-images.githubusercontent.com/13380485/125916018-e7f0fd6c-502d-4d63-bf94-67d9c1ff162f.png)

**Comment by leoschur** [comment]
This needs to be reimplemented on the dev branch.
